### ISSUE TITLE
Fix CSS link

### ISSUE THREAD

**Issue by gdedi001** [leighannajo/prj-rev-bwfs-dasmoto#4]
Your link here is incorrect
https://github.com/leighannajo/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's%20Arts%20and%20Crafts/index.html#L6

Make it this
`<link href="Resources/CSS/style.css" type="text/css" rel="stylesheet">`

**Comment by leighannajo** [comment]
Fixed, thank you!
